OnlineLibrary/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineLibrary.Models
{
    public class Book
    {
        [Key]
        public int id { get; set; }
        [Required]

        public string? book_name { get; set; }
        [Required]

        public string? author { get; set; }
        [Required]

        public string? book_genre { get; set; }
        [Required]

        public string? short_dicription { get; set; }
        [Required]

        public float? rating { get; set; }

        public int? number_of_views { get; set; }

    }
}

OnlineLibrary/Controllers/BooksController.cs
using OnlineLibrary.Data;
using OnlineLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Net;
using OnlineLibrary.Areas.Identity.Data;
using OnlineLibrary.Models;
using Microsoft.EntityFrameworkCore.Query;
using static System.Reflection.Metadata.BlobBuilder;

namespace OnlineLibrary.Controllers
{
    public class BooksController : Controller
    {
        private OnlineLibraryDbContext dtbs;

        private int storedBookId = 0;

        // Змініть це поле на об'єкт, що ініціалізується при кожному запиті
        public HistoryOfReadBooks historyOfReadBooks => new HistoryOfReadBooks();

        public BooksController(OnlineLibraryDbContext dtbs)
        {
            this.dtbs = dtbs;
        }

        public IActionResult Books()
        {
            var books = dtbs.Books.ToList();
            return View(books);
        }

        public IActionResult SortByName()
        {
            var books = dtbs.Books.OrderBy(b => b.book_name).ToList();
            return View(books);
        }

        public IActionResult AdminBooks()
        {
            var books = dtbs.Books.ToList();
            return View(books);
        }
        public ActionResult AddedToRead(int bookId, int readerId)
        {
            RegisteredReader regreader = new RegisteredReader();
            regreader = dtbs.RegisteredReaders.Find(readerId);
            Book readedbook = new Book();
            readedbook = dtbs.Books.Find(bookId);
            if (ModelState.IsValid)
            {
                HistoryOfReadBooks hisofread = new HistoryOfReadBooks()
                {
                    Books = readedbook,
                    RegisteredReaders = regreader,
                };
                dtbs.HistoryOfReadBooks.Add(hisofread);
                dtbs.SaveChanges();
            }
            return RedirectToAction("Books", "Books");
        }

        public IActionResult AddingNewBook()
        {
            return View();
        }
        
        public IActionResult EditBook()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddedBook(Book addedbook)
        {
            if (ModelState.IsValid)
            {
                bool bookExist = dtbs.Books.Any(p => p.book_name == addedbook.book_name);

                if (!bookExist)
                {
                    addedbook.number_of_views = 1;
                    dtbs.Books.Add(addedbook);
                    dtbs.SaveChanges();
                }
            }

            return RedirectToAction("AdminBooks", "Books");
        }

        [HttpPost]
        public ActionResult GetBookId(int bookId)
        {
            this.storedBookId = bookId;
            TempData["BookId"] = storedBookId;
            return RedirectToAction("EditBook");
        }

        [HttpPost]
        public ActionResult BookDelete(int bookId)
        {
            Book deletedBook = new Book();
            deletedBook = dtbs.Books.Find(bookId);
            dtbs.Books.Remove(deletedBook);
            dtbs.SaveChanges();
            return RedirectToAction("AdminBooks");
        }

        [HttpPost]
        public IActionResult EditBook(int id, string newBookName, string newAuthor, string newGenre, string newDiscription, float newRating)
        {
            Book editedBook = new Book();
            if (ModelState.IsValid)
            {
                editedBook = dtbs.Books.Find(id);
                editedBook.book_name = newBookName;
                editedBook.author = newAuthor;
                editedBook.book_genre = newGenre;
                editedBook.short_dicription = newDiscription;
                editedBook.rating = newRating;
                editedBook.number_of_views = 1;
                dtbs.Books.Update(editedBook);
                dtbs.SaveChanges();
                return RedirectToAction("AdminBooks", "Books");
            }
            return View();
        }
    }
}

OnlineLibrary/Controllers/LoginController.cs
using OnlineLibrary.Data;
using OnlineLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace OnlineLibrary.Controllers
{
    public class LoginController : Controller
    {
        private OnlineLibraryDbContext dtbs;

        public static bool IsAdmin = false;

        public LoginController(OnlineLibraryDbContext dtbs)
        {
            this.dtbs = dtbs;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(RegisteredReader registeredReader)
        {
            // Перевірка чи існує користувач із введеними ім'ям та паролем
            var Reader = dtbs.RegisteredReaders.FirstOrDefault(v => v.e_mail == registeredReader.e_mail && v.password == registeredReader.password);

            if (Reader != null)
            {
                // Користувач знайдений, перенаправляємо його на головну сторінку
                ProfileController.RegisteredReader = Reader;
                HttpContext.Session.SetString("Username", registeredReader.e_mail);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Неправильне ім'я користувача або пароль");
                ModelState.AddModelError(string.Empty, "Або Ваш акаунт не є зареєстрований");
                return View();
            }

        }

        
        [HttpPost]
        public IActionResult AdminLogin(Admin admin)
        {
            // Перевірка чи існує користувач із введеними ім'ям та паролем
            var adminUser = dtbs.Admin.FirstOrDefault(v => v.Email == admin.Email && v.Password == admin.Password);

            if (adminUser != null)
            {
                // Користувач знайдений, перенаправляємо його на головну сторінку
                ProfileController.admin = adminUser;
                IsAdmin = true;
                HttpContext.Session.SetString("Username", admin.Email);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Неправильне ім'я користувача або пароль");
                ModelState.AddModelError(string.Empty, "Або Ваш акаунт не є зареєстрований");
                return View();
            }

        }
    }
}

OnlineLibrary/Controllers/RegistrationController.cs
using OnlineLibrary.Data;
using OnlineLibrary.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Transactions;

namespace OnlineLibrary.Controllers
{
    public class RegistrationController : Controller
    {
        private OnlineLibraryDbContext dtbs;

        public RegistrationController(OnlineLibraryDbContext dtbs)
        {
            this.dtbs = dtbs;
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registration(RegisteredReader registeredReader)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = dtbs.Database.BeginTransaction())
                {
                    try
                    {
                        bool usExist = dtbs.RegisteredReaders.Any(p => p.e_mail == registeredReader.e_mail);

                        if (!usExist)
                        {
                            dtbs.RegisteredReaders.Add(registeredReader);
                            dtbs.SaveChanges();

                            RegisteredReader newReader = dtbs.RegisteredReaders.FirstOrDefault(p => p.e_mail == registeredReader.e_mail);

                        }
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        throw new Exception(ex.Message);
                    }
                }                              
            }
            return RedirectToAction("Login", "Login");
        }
    }
}

OnlineLibrary/Views/Shared/Books.cshtml
@model IEnumerable<Book>
@using OnlineLibrary.Controllers
<link rel="stylesheet" type="text/css" href="~/css/BooksStyle.css">

<div class="class">
<h1 class="title">Books</h1>
<div class="books">
<table>
    <thead>
        <form asp-action="SortByName" asp-controller="Books">
        </form>
                
        <tr>
            <th class="columnname1">Title</th>
            <th class="columnname2">Author</th>
            <th class="columnname3">Book genre</th>
            <th class="columnname4">Short dicription</th>
            <th class="columnname5">Rating</th>
            <th class="columnname7">Read it!</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td class="rowname1">@book.book_name</td>
                <td class="rowname2">@book.author</td>
                <td class="rowname3">@book.book_genre</td>
                <td class="rowname4">@book.short_dicription</td>
                <td class="rowname5">@book.rating</td>
                <td class="rowname7">
                    <form class="rowname7" asp-action="AddedToRead" asp-controller="Books" method="post">
                        <input type="hidden" name="bookId" value="@book.id" />
                        <input type="hidden" name="readerId" value="@ProfileController.RegisteredReader.id"  />
                        <input type="submit" class="btn btn-primary read-button" data-id="@book.id" name="newBookRead" value="Read" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>

OnlineLibrary/Views/Shared/_Layout.cshtml
@using OnlineLibrary.Controllers
@using OnlineLibrary.Models;
@using OnlineLibrary.Data;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineLibrary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-area="" asp-controller="Home" asp-action="Index">OnlineLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         
                        @{
                            var username = Context.Session.GetString("Username");
                            if (LoginController.IsAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="AdminBooks">Edit books catalog</a>
                                </li>
                                <div class="buttons">  
                                    <li class="nav-item">
                                    <form asp-action="AdminLogOut" asp-controller="Profile" method="post">
                                            <button type="submit" class="btn">Log out</button>
                                    </form>
                                    </li>
                                </div>
                            }
                            else if (string.IsNullOrEmpty(username))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                            <div class="buttons">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Registration">Registration</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Log in</a>
                                </li>
                            </div>
                            }                            
                            else
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Books">Books catalog</a>
                            </li>
                            <div class="buttons">                            
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Profile">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <form asp-action="LogOut" asp-controller="Profile" method="post">
                                        <button type="submit" class="btn">Log out</button>
                                    </form>
                                </li>
                            </div>
                            }
                         }                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineLibrary
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>